let stream=null,calibration=null,measurementFrame=null,validationFrame=null;
let measurementPoints=[],validationPoints=[],validationResults=[],validationIndex=0,validationStarted=false;
const O=[["Car",5,3],["AirPods",5.5,2],["Bigfoot",4.3,6.5],["Ruby",3.5,6],["Pepper",3.7,8.7],["Shoe polish",10,4.5],["Container",8,5.5],["Sardines",7,2.4],["Key",2.5,1],["Mouse",5,2.5],["Playdoh",4.7,3.8],["Bose",8,9.5],["Oil",6.5,11.5],["Juice",5.5,10.5],["Roku",4,1.6],["Lotion",3.5,14],["Vitamin",9,10.5],["Cup",7,13],["Brownie",9,1.5],["Egg cup",5,7.5]].map(x=>({name:x[0],width:x[1],height:x[2]}));
const $=id=>document.getElementById(id);

document.querySelectorAll(".step-tab").forEach(b=>b.onclick=()=>showStep(b.dataset.step));
function showStep(id){document.querySelectorAll(".step-tab").forEach(b=>b.classList.toggle("active",b.dataset.step===id));document.querySelectorAll(".step-panel").forEach(p=>p.classList.toggle("active-panel",p.id===id));}

$("startCameraBtn").onclick=startCamera;$("refreshCamerasBtn").onclick=loadCameras;$("stopCameraBtn").onclick=stopCamera;$("cameraSelect").onchange=()=>{if(stream)startCamera();};
async function loadCameras(){const d=await navigator.mediaDevices.enumerateDevices(),c=d.filter(x=>x.kind==="videoinput"),s=$("cameraSelect"),old=s.value;s.innerHTML="";c.forEach((x,i)=>{let o=document.createElement("option");o.value=x.deviceId;o.textContent=x.label||`Camera ${i+1}`;s.appendChild(o)});if(old&&[...s.options].some(o=>o.value===old))s.value=old;}
async function startCamera(){try{stopCamera();let video={width:{ideal:1920},height:{ideal:1080}};if($("cameraSelect").value)video.deviceId={exact:$("cameraSelect").value};stream=await navigator.mediaDevices.getUserMedia({video,audio:false});$("video").srcObject=stream;await $("video").play();await loadCameras();$("cameraStatus").textContent=`Camera started: ${$("video").videoWidth} × ${$("video").videoHeight}`;}catch(e){$("cameraStatus").textContent="Camera error: "+e.message;}}
function stopCamera(){if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;$("video").srcObject=null;}
function capture(c){if(!stream||!$("video").videoWidth)throw Error("Start the camera first.");c.width=$("video").videoWidth;c.height=$("video").videoHeight;c.getContext("2d").drawImage($("video"),0,0,c.width,c.height);}

$("saveCalibrationBtn").onclick=()=>{let fx=+$("fxInput").value,fy=+$("fyInput").value,cx=+$("cxInput").value,cy=+$("cyInput").value,width=+$("calWidthInput").value,height=+$("calHeightInput").value,rms=$("rmsInput").value?+$("rmsInput").value:null;if(![fx,fy,cx,cy,width,height].every(Number.isFinite)||fx<=0||fy<=0){$("calibrationStatus").textContent="Enter valid calibration values.";return;}calibration={fx,fy,cx,cy,width,height,rms};localStorage.setItem("module2Calibration",JSON.stringify(calibration));showCal();$("calibrationStatus").textContent="Calibration saved. Steps 2 and 3 are ready.";};
$("clearCalibrationBtn").onclick=()=>{calibration=null;localStorage.removeItem("module2Calibration");$("calibrationResults").classList.add("hidden");};
function showCal(){$("fxValue").textContent=calibration.fx.toFixed(2);$("fyValue").textContent=calibration.fy.toFixed(2);$("cxValue").textContent=calibration.cx.toFixed(2);$("cyValue").textContent=calibration.cy.toFixed(2);$("resolutionValue").textContent=`${calibration.width} × ${calibration.height}`;$("rmsValue").textContent=calibration.rms==null?"-":calibration.rms.toFixed(4)+" px";$("calibrationResults").classList.remove("hidden");}
function loadCal(){let s=localStorage.getItem("module2Calibration");if(!s)return;calibration=JSON.parse(s);$("fxInput").value=calibration.fx;$("fyInput").value=calibration.fy;$("cxInput").value=calibration.cx;$("cyInput").value=calibration.cy;$("calWidthInput").value=calibration.width;$("calHeightInput").value=calibration.height;if(calibration.rms!=null)$("rmsInput").value=calibration.rms;showCal();}

function pnt(e,c){let r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height};}function d(a,b){return Math.hypot(b.x-a.x,b.y-a.y);}
function draw(c,pts){let x=c.getContext("2d");x.strokeStyle=x.fillStyle="#00ff66";x.lineWidth=4;x.font="24px Arial";pts.forEach((p,i)=>{x.beginPath();x.arc(p.x,p.y,8,0,Math.PI*2);x.fill();x.fillText(String(i+1),p.x+10,p.y-10)});if(pts.length>1){x.beginPath();x.moveTo(pts[0].x,pts[0].y);for(let i=1;i<pts.length;i++)x.lineTo(pts[i].x,pts[i].y);if(pts.length===4)x.closePath();x.stroke();}}
function restore(c,url,pts){if(!url)return;let i=new Image();i.onload=()=>{c.getContext("2d").drawImage(i,0,0,c.width,c.height);draw(c,pts)};i.src=url;}
function calc(pts,z,c){if(!calibration)throw Error("Save Step 1 calibration first.");if(pts.length!==4)throw Error("Select exactly 4 corners.");let[tl,tr,br,bl]=pts,wp=(d(tl,tr)+d(bl,br))/2,hp=(d(tl,bl)+d(tr,br))/2,fx=calibration.fx*c.width/calibration.width,fy=calibration.fy*c.height/calibration.height;return{wp,hp,w:wp*z/fx*100,h:hp*z/fy*100};}

$("captureObjectBtn").onclick=()=>{try{let c=$("measurementCanvas");capture(c);measurementFrame=c.toDataURL();measurementPoints=[];$("measurementStatus").textContent="Captured. Click the 4 corners.";}catch(e){$("measurementStatus").textContent=e.message;}};
$("measurementCanvas").onclick=e=>{if(!measurementFrame||measurementPoints.length>=4)return;measurementPoints.push(pnt(e,$("measurementCanvas")));restore($("measurementCanvas"),measurementFrame,measurementPoints);};
$("resetCornersBtn").onclick=()=>{measurementPoints=[];restore($("measurementCanvas"),measurementFrame,measurementPoints);};
$("calculateObjectBtn").onclick=()=>{try{let r=calc(measurementPoints,+$("step2Distance").value,$("measurementCanvas"));$("pixelWidthResult").textContent=r.wp.toFixed(2)+" px";$("pixelHeightResult").textContent=r.hp.toFixed(2)+" px";$("widthResult").textContent=r.w.toFixed(2)+" cm";$("heightResult").textContent=r.h.toFixed(2)+" cm";$("measurementResults").classList.remove("hidden");}catch(e){$("measurementStatus").textContent=e.message;}};

$("validationMode").onchange=()=>$("manualFields").classList.toggle("hidden",$("validationMode").value!=="manual");
$("beginValidationBtn").onclick=()=>{if(!calibration){$("validationStatus").textContent="Save calibration first.";return;}validationResults=[];validationIndex=0;validationStarted=true;$("validationTable").querySelector("tbody").innerHTML="";updateObj();};
function truth(){if($("validationMode").value==="predefined")return O[validationIndex]||null;let name=$("manualName").value.trim(),width=+$("manualWidth").value,height=+$("manualHeight").value;return name&&width>0&&height>0?{name,width,height}:null;}
function updateObj(){if($("validationMode").value==="predefined"){let o=O[validationIndex];$("currentObject").innerHTML=o?`<b>${validationIndex+1}/20 - ${o.name}</b><br>Actual width: ${o.width.toFixed(2)} cm | Actual height: ${o.height.toFixed(2)} cm`:"All 20 objects completed.";}else $("currentObject").textContent="Enter object information above.";}
$("captureValidationBtn").onclick=()=>{if(!validationStarted){$("validationStatus").textContent="Press Begin Validation first.";return;}if(!truth()){$("validationStatus").textContent="Enter valid object information.";return;}try{let c=$("validationCanvas");capture(c);validationFrame=c.toDataURL();validationPoints=[];$("validationStatus").textContent="Captured. Click the 4 corners.";}catch(e){$("validationStatus").textContent=e.message;}};
$("validationCanvas").onclick=e=>{if(!validationFrame||validationPoints.length>=4)return;validationPoints.push(pnt(e,$("validationCanvas")));restore($("validationCanvas"),validationFrame,validationPoints);};
$("resetValidationCornersBtn").onclick=()=>{validationPoints=[];restore($("validationCanvas"),validationFrame,validationPoints);};
$("saveValidationBtn").onclick=()=>{let t=truth();if(!t)return;try{let e=calc(validationPoints,+$("validationDistance").value,$("validationCanvas")),we=e.w-t.width,he=e.h-t.height,wa=Math.abs(we),ha=Math.abs(he),wp=wa/t.width*100,hp=ha/t.height*100,r={measurement:validationResults.length+1,object:t.name,distance:+$("validationDistance").value,actualWidth:t.width,cameraWidth:e.w,widthError:we,widthAbs:wa,widthPct:wp,actualHeight:t.height,cameraHeight:e.h,heightError:he,heightAbs:ha,heightPct:hp};validationResults.push(r);let tr=document.createElement("tr");tr.innerHTML=`<td>${r.measurement}</td><td>${r.object}</td><td>${r.actualWidth.toFixed(2)}</td><td>${r.cameraWidth.toFixed(2)}</td><td>${r.actualHeight.toFixed(2)}</td><td>${r.cameraHeight.toFixed(2)}</td><td>${r.widthPct.toFixed(2)}%</td><td>${r.heightPct.toFixed(2)}%</td>`;$("validationTable").querySelector("tbody").appendChild(tr);validationIndex++;updateObj();}catch(e){$("validationStatus").textContent=e.message;}};
$("clearValidationBtn").onclick=()=>{validationResults=[];validationIndex=0;validationStarted=false;$("validationTable").querySelector("tbody").innerHTML="";updateObj();};
function mean(a){return a.reduce((x,y)=>x+y,0)/a.length}function rmse(a){return Math.sqrt(mean(a.map(v=>v*v)))}function std(a){let m=mean(a);return Math.sqrt(mean(a.map(v=>(v-m)**2)))}
$("finishValidationBtn").onclick=()=>{if(!validationResults.length)return;let we=validationResults.map(r=>r.widthError),he=validationResults.map(r=>r.heightError),wa=validationResults.map(r=>r.widthAbs),ha=validationResults.map(r=>r.heightAbs),wp=validationResults.map(r=>r.widthPct),hp=validationResults.map(r=>r.heightPct),wM=mean(we),hM=mean(he),wA=mean(wa),hA=mean(ha),wR=rmse(we),hR=rmse(he),wP=mean(wp),hP=mean(hp),wS=std(we),hS=std(he),ov=(wP+hP)/2;$("reportCount").textContent=validationResults.length;$("reportWMean").textContent=wM.toFixed(3)+" cm";$("reportWMAE").textContent=wA.toFixed(3)+" cm";$("reportWRMSE").textContent=wR.toFixed(3)+" cm";$("reportWMAPE").textContent=wP.toFixed(2)+"%";$("reportWStd").textContent=wS.toFixed(3)+" cm";$("reportHMean").textContent=hM.toFixed(3)+" cm";$("reportHMAE").textContent=hA.toFixed(3)+" cm";$("reportHRMSE").textContent=hR.toFixed(3)+" cm";$("reportHMAPE").textContent=hP.toFixed(2)+"%";$("reportHStd").textContent=hS.toFixed(3)+" cm";$("reportOverall").textContent=ov.toFixed(2)+"%";$("reportSummary").innerHTML=`Validated using <b>${validationResults.length}</b> measurement(s). Overall average percentage error: <b>${ov.toFixed(2)}%</b>.`;let tb=$("reportTable").querySelector("tbody");tb.innerHTML="";validationResults.forEach(r=>{let tr=document.createElement("tr");tr.innerHTML=`<td>${r.measurement}</td><td>${r.object}</td><td>${r.actualWidth.toFixed(2)} cm</td><td>${r.cameraWidth.toFixed(2)} cm</td><td>${r.actualHeight.toFixed(2)} cm</td><td>${r.cameraHeight.toFixed(2)} cm</td>`;tb.appendChild(tr)});$("reportStats").classList.remove("hidden");showStep("report");};
$("downloadCsvBtn").onclick=()=>{let rows=[["measurement","object_name","distance_m","actual_width_cm","estimated_width_cm","width_error_cm","width_absolute_error_cm","width_percentage_error","actual_height_cm","estimated_height_cm","height_error_cm","height_absolute_error_cm","height_percentage_error"]];validationResults.forEach(r=>rows.push([r.measurement,r.object,r.distance,r.actualWidth,r.cameraWidth,r.widthError,r.widthAbs,r.widthPct,r.actualHeight,r.cameraHeight,r.heightError,r.heightAbs,r.heightPct]));let csv=rows.map(row=>row.join(",")).join("\\n"),blob=new Blob([csv],{type:"text/csv"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="step3_validation_results_web.csv";a.click();URL.revokeObjectURL(url);};
$("printReportBtn").onclick=()=>window.print();
window.onload=()=>{loadCal();$("validationMode").dispatchEvent(new Event("change"));};
